# Generated by Django 5.0.14 on 2026-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
