# Generated by Django 5.0.14 on 2026-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_max_experience_years_job_min_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
    ]
